[flutter_appauth][flutter_appauth_platform_interface] Add preferEphemeralSession option to logout
MaikuB/flutter_appauth pull request #349
Opened 2022-07-12 16:10 UTC by ziegler-daniel

Hi,

at the moment it is possible to pass the option `preferEphemeralSession: true` to the sign in call, but not to the end session call. Therefore, before every logout a pop-up like this is shown to the user:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/44165453/178540323-c9236144-b1ba-4f49-9752-27e96f5bb61e.png">

If no pop-up was displayed before the login, it would be nicer if there is also none before the logout. So, I added the functionality to set the `preferEphemeralSession` option also for the end session call.

It would be nice if this feature could be included into the library.

2022-07-18 09:39 UTC, MaikuB commented on flutter_appauth_platform_interface/lib/src/end_session_request.dart
> +  bool? preferEphemeralSession;
Can this made non-nullable?

2022-07-18 13:37 UTC, ziegler-daniel commented on flutter_appauth_platform_interface/lib/src/end_session_request.dart
> +  bool? preferEphemeralSession;
Yes, I changed it accordingly

2022-07-19 11:58 UTC, MaikuB commented
Whilst the popup is removed, using an ephemeral session means a "private" browser is used. Users won't actually get signed out as a result. The following is a recording from sigining in and signing out normally using the example

https://user-images.githubusercontent.com/25263378/179742937-13f7d3ab-f223-4599-b3e3-c79077dc3c7f.mov

At the end I attempt to sign in again to show that the browser no longer knows I've been signed in as I'm prompted to sign in again. Now let's repeat this with the end session request where `preferEphemeralSession` is set to `true`


https://user-images.githubusercontent.com/25263378/179743538-224fdab3-ec44-4de0-97b8-decdd99a38fc.mov

After signing out, I've tried to sign in again and still recognises that I'm signed in. This effectively means the end session request hasn't really done anything. With this is in mind and do let me know if I've missed something, I don't see a reason why this feature added by the PR since the user's session is being kept.

2022-07-19 12:25 UTC, dconlisk commented
Ah, that's a shame that it doesn't work. @MaikuB do you know if it's possible to update the text in the popup from "Sign In" to "Sign Out" when ending the session?

2022-07-19 12:28 UTC, dconlisk commented
@MaikuB I was afraid that might be the case - thanks!

2022-07-20 06:20 UTC, ziegler-daniel commented
@MaikuB thank you for your response. In my opinion the option `preferEphemeralSession = true` must only be used for the logout call, if it was also used for the sign in call. According to the [apple documentation](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1410529-ephemeral) no data is stored in an ephemeral session. So, if you use `preferEphemeralSession = true` for sign in, you won't get the described problem. Using different values for `preferEphemeralSession` for sign in and end session call would be like using two different browsers for the two calls.

The end session call invalidates the current refresh token regardless of the `preferEphemeralSession` option.

I can add this to the documentation to prevent misunderstandings.

2022-07-20 09:39 UTC, MaikuB commented
@ziegler-daniel ok gotcha. Updating the documentation around using this makes sense to me

2022-07-20 15:15 UTC, ziegler-daniel commented
> 

Sure, I added some documentation at the `EndSessionRequest` and in the readme file. Is that okay with you?

2022-07-21 09:36 UTC, MaikuB requested changes
Yes placing the documentation like you have is fine though I left comments on the usage of commas :)

2022-07-21 09:36 UTC, MaikuB commented on flutter_appauth/README.md
> +The option `preferEphemeralSession = true` must only be used for the end session call, if it is also used for the sign in call.
the comma isn't needed before the "if"

2022-07-21 09:36 UTC, MaikuB commented on flutter_appauth/README.md
> +Otherwise there will be still an active login session in the browser.
in this case, a comma should be after "Otherwise" :)

2022-07-21 11:27 UTC, ziegler-daniel commented
> Yes placing the documentation like you have is fine though I left comments on the usage of commas :)

Thank you for you feedback. I adjusted it.

2022-07-22 23:30 UTC, MaikuB approved these changes

2022-07-22 23:30 UTC, merged

2022-07-25 23:17 UTC, fbernaly commented
@ziegler-daniel: Thanks for this PR. This is what I needed for my app.